version: '3.8'
services:
  mariadb:
    image: mariadb:10.4.24
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MARIADB_ROOT_PASSWORD=$DB_PASSWORD
      - MARIADB_DATABASE=$DB_NAME
    expose:
      - 3306
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
  api:
    depends_on:
      - mariadb
    build: ./
    container_name: api_c
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mariadb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    links: 
      - mariadb
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    